// Scenario: a campus food stall selling a packed rice meal.
//
// EVERY number here is `assumption: true`. None is a measured Ghanaian
// statistic: they are illustrative placeholders chosen so the simulation
// behaves plausibly, and each is lecturer-editable. Replace a value with
// `sourced(value, "citation")` once there is a real source (brief §0.5).
import { assumed, type Param } from "../params.ts";
import type { EventDef, Scenario } from "../types.ts";

const PLACEHOLDER = "Illustrative placeholder, not a measured figure. Lecturer to confirm or replace with a sourced value.";
const DESIGN = "Game-design parameter controlling model behaviour, not a real-world statistic.";

const a = (value: number): Param => assumed(value, PLACEHOLDER);
const d = (value: number): Param => assumed(value, DESIGN);

const events: EventDef[] = [
  {
    id: "supplier_price_rise",
    name: "Supplier price rise",
    type: "operational",
    scope: "cohort",
    description: "Rice and oil prices rise at the market. Every stall buying from the same traders pays more.",
    probability: d(0.15),
    trigger: null,
    duration: 2,
    severity: "high",
    affectedMetrics: ["unit cost", "margin"],
    impact: [{ metric: "supplier_cost", value: 1.25 }],
    responses: [
      { id: "absorb", label: "Absorb the cost", description: "Keep buying as usual and accept thinner margins.", cost: a(0), effects: [{ metric: "supplier_cost", value: 1.25 }] },
      { id: "negotiate_bulk", label: "Negotiate a bulk price", description: "Commit to buying in bulk for a better rate; costs a deposit.", cost: a(20000), effects: [{ metric: "supplier_cost", value: 1.12 }] },
      { id: "smaller_portions", label: "Serve smaller portions", description: "Use less per plate. Cheaper, but customers may notice.", cost: a(0), effects: [{ metric: "supplier_cost", value: 1.05 }, { metric: "quality", value: -0.12 }, { metric: "reputation", value: -3 }] },
    ],
    defaultResponseId: "absorb",
  },
  {
    id: "momo_outage",
    name: "Mobile Money outage",
    type: "infrastructure",
    scope: "cohort",
    description: "Mobile Money payments fail across the area for most of the week. Customers without cash buy less.",
    probability: d(0.12),
    trigger: null,
    duration: 2,
    severity: "medium",
    affectedMetrics: ["demand"],
    impact: [{ metric: "demand", value: 0.85 }],
    responses: [
      { id: "cash_only", label: "Cash only", description: "Accept only cash until the network is back.", cost: a(0), effects: [{ metric: "demand", value: 0.9 }] },
      { id: "trust_credit", label: "Let regulars pay later", description: "Informal credit for known customers. Keeps sales, but some will never pay.", cost: a(0), effects: [{ metric: "demand", value: 0.98 }, { metric: "fixed_cost", value: 9000 }, { metric: "reputation", value: 1 }] },
    ],
    defaultResponseId: "cash_only",
  },
  {
    id: "power_outage",
    name: "Power outages",
    type: "infrastructure",
    scope: "cohort",
    description: "Scheduled and unscheduled power cuts make it hard to cook and keep food cold.",
    probability: d(0.18),
    trigger: null,
    duration: 2,
    severity: "medium",
    affectedMetrics: ["capacity", "spoilage"],
    impact: [{ metric: "capacity", value: 0.7 }, { metric: "spoilage", value: 1.3 }],
    responses: [
      { id: "wait", label: "Work around it", description: "Cook when there is power.", cost: a(0), effects: [{ metric: "capacity", value: 0.75 }, { metric: "spoilage", value: 1.3 }] },
      { id: "rent_generator", label: "Rent a generator", description: "Near-normal capacity, but fuel and rent every week.", cost: a(5000), effects: [{ metric: "capacity", value: 0.95 }, { metric: "fixed_cost", value: 25000 }] },
      { id: "charcoal", label: "Switch to charcoal", description: "Keep cooking on charcoal: slower and a little more costly per plate.", cost: a(3000), effects: [{ metric: "capacity", value: 0.85 }, { metric: "per_unit_cost", value: 80 }, { metric: "spoilage", value: 1.3 }] },
    ],
    defaultResponseId: "wait",
  },
  {
    id: "exam_period",
    name: "Examination period",
    type: "market",
    scope: "cohort",
    description: "Students are studying and eating in hostels; fewer come out to buy.",
    probability: d(0.15),
    trigger: null,
    duration: 2,
    severity: "medium",
    affectedMetrics: ["demand (students)"],
    impact: [{ metric: "demand", value: 0.75, segmentId: "students" }],
    responses: [
      { id: "accept", label: "Accept the dip", description: "Carry on as normal.", cost: a(0), effects: [{ metric: "demand", value: 0.75, segmentId: "students" }] },
      { id: "hostel_delivery", label: "Deliver to hostels", description: "Take orders by phone and deliver in the evening.", cost: a(4000), effects: [{ metric: "demand", value: 0.95, segmentId: "students" }, { metric: "fixed_cost", value: 15000 }] },
    ],
    defaultResponseId: "accept",
  },
  {
    id: "competitor_price_cut",
    name: "Competitor price war",
    type: "competitive",
    scope: "cohort",
    description: "Established sellers cut prices to win back customers.",
    probability: d(0.14),
    trigger: null,
    duration: 2,
    severity: "high",
    affectedMetrics: ["competitor prices", "demand"],
    impact: [{ metric: "competitor_price", value: 0.85 }],
    responses: [
      { id: "hold", label: "Hold your price", description: "Do nothing different.", cost: a(0), effects: [{ metric: "competitor_price", value: 0.85 }] },
      { id: "loyalty_card", label: "Start a loyalty card", description: "Every 10th meal free: makes regulars less likely to switch.", cost: a(3000), effects: [{ metric: "competitor_price", value: 0.85 }, { metric: "switching_cost", value: 0.2 }, { metric: "per_unit_cost", value: 150 }] },
      { id: "quality_story", label: "Market your quality", description: "Spend on showing why your food is worth more.", cost: a(8000), effects: [{ metric: "competitor_price", value: 0.85 }, { metric: "marketing_effectiveness", value: 1.3 }, { metric: "quality", value: 0.05 }] },
    ],
    defaultResponseId: "hold",
  },
  {
    id: "new_entrant",
    name: "New kiosk opens",
    type: "competitive",
    scope: "cohort",
    description: "A new food kiosk opens close to the main lecture halls.",
    probability: d(0.12),
    trigger: null,
    duration: 2,
    severity: "medium",
    affectedMetrics: ["competition"],
    impact: [{ metric: "new_competitor", value: 1, competitorId: "new_kiosk" }],
    responses: [
      { id: "ignore", label: "Ignore them", description: "They may not last.", cost: a(0), effects: [] },
      { id: "differentiate", label: "Differentiate", description: "Add a side dish your regulars ask for.", cost: a(15000), effects: [{ metric: "quality", value: 0.06 }] },
    ],
    defaultResponseId: "ignore",
    oncePerRun: true,
  },
  {
    id: "transport_cost_rise",
    name: "Transport fares rise",
    type: "operational",
    scope: "cohort",
    description: "Trotro and taxi fares go up, so getting stock from the market costs more.",
    probability: d(0.14),
    trigger: null,
    duration: 2,
    severity: "low",
    affectedMetrics: ["cost per unit"],
    impact: [{ metric: "per_unit_cost", value: 120 }],
    responses: [
      { id: "absorb", label: "Absorb it", description: "Keep making separate trips.", cost: a(0), effects: [{ metric: "per_unit_cost", value: 120 }] },
      { id: "share_transport", label: "Share transport", description: "Arrange shared trips with other sellers: a weekly fee, lower cost per plate.", cost: a(0), effects: [{ metric: "per_unit_cost", value: 40 }, { metric: "fixed_cost", value: 8000 }] },
    ],
    defaultResponseId: "absorb",
  },
  {
    id: "health_inspection",
    name: "Food hygiene inspection",
    type: "financial",
    scope: "group",
    description: "An environmental health officer inspects the stall and asks for proof of a food handler's certificate.",
    probability: d(0.12),
    trigger: null,
    duration: 2,
    severity: "high",
    affectedMetrics: ["costs", "reputation"],
    impact: [{ metric: "reputation", value: -2 }],
    responses: [
      { id: "comply", label: "Get certified", description: "Pay for medical screening and the certificate.", cost: a(20000), effects: [{ metric: "reputation", value: 2 }] },
      { id: "ignore", label: "Ignore it", description: "Hope they do not come back.", cost: a(0), effects: [{ metric: "fixed_cost", value: 40000 }, { metric: "reputation", value: -6 }] },
    ],
    defaultResponseId: "ignore",
    oncePerRun: true,
  },
  {
    id: "viral_post",
    name: "Your food goes viral",
    type: "market",
    scope: "group",
    description: "A student's post about your food is shared widely on campus WhatsApp groups.",
    probability: d(0.2),
    trigger: { metric: "reputation", op: "gte", value: 62 },
    duration: 2,
    severity: "low",
    affectedMetrics: ["awareness"],
    impact: [{ metric: "awareness", value: 300 }],
    responses: [
      { id: "ride_wave", label: "Ride the wave", description: "Post daily menus and offers while people are talking about you.", cost: a(5000), effects: [{ metric: "marketing_effectiveness", value: 1.5 }] },
      { id: "carry_on", label: "Carry on", description: "Enjoy it and carry on as normal.", cost: a(0), effects: [] },
    ],
    defaultResponseId: "carry_on",
    oncePerRun: true,
  },
  {
    id: "storage_failure",
    name: "Cold storage breaks down",
    type: "operational",
    scope: "group",
    description: "The freezer you rely on breaks while holding a lot of stock.",
    probability: d(0.25),
    trigger: { metric: "inventory_units", op: "gte", value: 250 },
    duration: 2,
    severity: "medium",
    affectedMetrics: ["spoilage"],
    impact: [{ metric: "spoilage", value: 2 }],
    responses: [
      { id: "repair", label: "Pay for repair", description: "Fix it properly.", cost: a(25000), effects: [] },
      { id: "improvise", label: "Improvise", description: "Borrow space in a neighbour's fridge when you can.", cost: a(0), effects: [{ metric: "spoilage", value: 1.5 }] },
    ],
    defaultResponseId: "improvise",
  },
];

export const campusFoodStall: Scenario = {
  id: "campus-food-stall",
  version: 1,
  name: "Campus food stall",
  family: "food",
  description:
    "Run a small stall selling packed rice meals to students and workers near campus. Food is bought from suppliers, cooked in limited batches, and spoils if unsold.",
  periodLabel: "week",
  periodCount: assumed(6, "Default course length for the simulation: about one period per week (brief §3, Slice B)."),
  startingCapital: a(400000),
  products: [
    {
      id: "rice_pack",
      name: "Packed rice meal",
      unit: "pack",
      referencePrice: a(2500),
      perUnitCost: a(150),
      defaultQualityTier: "standard",
    },
  ],
  segments: [
    {
      id: "students",
      name: "Students",
      marketSize: a(1500),
      footfallReach: a(60),
      referencePriceMult: a(0.9),
      priceSensitivity: d(0.9),
      qualitySensitivity: d(0.4),
      brandSensitivity: d(0.3),
      switchingCost: d(0.15),
      purchaseFrequency: a(1.6),
      retention: d(0.7),
      conversionProbability: d(0.28),
    },
    {
      id: "workers",
      name: "Campus staff and workers",
      marketSize: a(400),
      footfallReach: a(25),
      referencePriceMult: a(1.1),
      priceSensitivity: d(0.5),
      qualitySensitivity: d(0.7),
      brandSensitivity: d(0.5),
      switchingCost: d(0.35),
      purchaseFrequency: a(2.2),
      retention: d(0.8),
      conversionProbability: d(0.22),
    },
  ],
  qualityTiers: [
    { id: "basic", label: "Basic", unitCostMult: a(0.85), quality: d(0.35) },
    { id: "standard", label: "Standard", unitCostMult: a(1), quality: d(0.55) },
    { id: "premium", label: "Premium", unitCostMult: a(1.3), quality: d(0.8) },
  ],
  suppliers: [
    {
      id: "market_trader",
      name: "Market trader",
      informal: true,
      unitPrice: { rice_pack: a(1200) },
      leadTimePeriods: d(0),
      capacityUnits: a(800),
      disruptionProbability: a(0.12),
      reliability: a(0.7),
    },
    {
      id: "wholesaler",
      name: "Registered wholesaler",
      informal: false,
      unitPrice: { rice_pack: a(1050) },
      leadTimePeriods: d(1),
      capacityUnits: a(3000),
      disruptionProbability: a(0.04),
      reliability: a(0.9),
    },
  ],
  competitors: [
    {
      id: "chop_bar",
      name: "Auntie's chop bar",
      informal: true,
      price: a(2000),
      unitCost: a(1300),
      quality: d(0.5),
      capacityUnits: a(1100),
      reputation: d(62),
      marketingStrength: d(0.6),
      responseStrategy: "steady",
    },
    {
      id: "campus_canteen",
      name: "Campus canteen",
      informal: false,
      price: a(2800),
      unitCost: a(1600),
      quality: d(0.6),
      capacityUnits: a(1500),
      reputation: d(55),
      marketingStrength: d(0.5),
      responseStrategy: "price_matcher",
    },
    {
      id: "new_kiosk",
      name: "New kiosk",
      informal: true,
      price: a(2200),
      unitCost: a(1250),
      quality: d(0.5),
      capacityUnits: a(600),
      reputation: d(45),
      marketingStrength: d(0.4),
      responseStrategy: "aggressive",
      entersViaEvent: true,
    },
  ],
  fixedCosts: [
    { id: "stall_rent", label: "Stall rent", amount: a(30000) },
    { id: "helper_wage", label: "Helper's wage", amount: a(40000) },
    { id: "gas_utilities", label: "Gas, water and utilities", amount: a(15000) },
  ],
  operations: {
    capacityUnitsPerPeriod: a(700),
    backordersEnabled: false,
    spoilageRate: a(0.3),
    maxOrderUnits: d(3000),
    stockoutChurn: d(0.4),
    lowQualityComplaintRate: d(0.08),
  },
  marketing: {
    costPerReach: a(50),
    awarenessDecay: d(0.2),
    leadRate: d(0.35),
    referralRate: d(0.08),
  },
  noise: { demandSigma: d(0.12) },
  reputation: { initial: d(50) },
  eventSettings: {
    frequency: assumed(1, "Lecturer dial: 1 = normal, 0 = no random events, 2 = twice as often."),
    firstEventPeriod: d(2),
    maxNewCohortEventsPerPeriod: d(2),
  },
  events,
};
