/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioGroupRouteImport } from './routes/studio/group'
import { Route as StudioOpportunityRouteImport } from './routes/studio/opportunity'
import { Route as StudioSelectRouteImport } from './routes/studio/select'
import { Route as StudioVentureRouteImport } from './routes/studio/venture'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioGroupRoute = StudioGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => StudioRoute,
} as any)
const StudioOpportunityRoute = StudioOpportunityRouteImport.update({
  id: '/opportunity',
  path: '/opportunity',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSelectRoute = StudioSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => StudioRoute,
} as any)
const StudioVentureRoute = StudioVentureRouteImport.update({
  id: '/venture',
  path: '/venture',
  getParentRoute: () => StudioRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/group': typeof StudioGroupRoute
  '/studio/opportunity': typeof StudioOpportunityRoute
  '/studio/select': typeof StudioSelectRoute
  '/studio/venture': typeof StudioVentureRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/studio/group': typeof StudioGroupRoute
  '/studio/opportunity': typeof StudioOpportunityRoute
  '/studio/select': typeof StudioSelectRoute
  '/studio/venture': typeof StudioVentureRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/group': typeof StudioGroupRoute
  '/studio/opportunity': typeof StudioOpportunityRoute
  '/studio/select': typeof StudioSelectRoute
  '/studio/venture': typeof StudioVentureRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/studio'
    | '/studio/group'
    | '/studio/opportunity'
    | '/studio/select'
    | '/studio/venture'
    | '/studio/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/studio/group'
    | '/studio/opportunity'
    | '/studio/select'
    | '/studio/venture'
    | '/studio'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/studio'
    | '/studio/group'
    | '/studio/opportunity'
    | '/studio/select'
    | '/studio/venture'
    | '/studio/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/group': {
      id: '/studio/group'
      path: '/group'
      fullPath: '/studio/group'
      preLoaderRoute: typeof StudioGroupRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/opportunity': {
      id: '/studio/opportunity'
      path: '/opportunity'
      fullPath: '/studio/opportunity'
      preLoaderRoute: typeof StudioOpportunityRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/select': {
      id: '/studio/select'
      path: '/select'
      fullPath: '/studio/select'
      preLoaderRoute: typeof StudioSelectRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/venture': {
      id: '/studio/venture'
      path: '/venture'
      fullPath: '/studio/venture'
      preLoaderRoute: typeof StudioVentureRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioGroupRoute: typeof StudioGroupRoute
  StudioOpportunityRoute: typeof StudioOpportunityRoute
  StudioSelectRoute: typeof StudioSelectRoute
  StudioVentureRoute: typeof StudioVentureRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioGroupRoute: StudioGroupRoute,
  StudioOpportunityRoute: StudioOpportunityRoute,
  StudioSelectRoute: StudioSelectRoute,
  StudioVentureRoute: StudioVentureRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
