/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LecturerRouteImport } from './routes/lecturer'
import { Route as LecturerSetupRouteImport } from './routes/lecturer-setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as RepRouteImport } from './routes/rep'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as LecturerIndexRouteImport } from './routes/lecturer/index'
import { Route as LecturerActivityRouteImport } from './routes/lecturer/activity'
import { Route as LecturerClassesRouteImport } from './routes/lecturer/classes'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioClassRouteImport } from './routes/studio/class'
import { Route as StudioGroupRouteImport } from './routes/studio/group'
import { Route as StudioJourneyRouteImport } from './routes/studio/journey'
import { Route as StudioOpportunityRouteImport } from './routes/studio/opportunity'
import { Route as StudioSelectRouteImport } from './routes/studio/select'
import { Route as StudioSimulationRouteImport } from './routes/studio/simulation'
import { Route as StudioVentureRouteImport } from './routes/studio/venture'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LecturerGroupsGroupIdRouteImport } from './routes/lecturer/groups.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerRoute = LecturerRouteImport.update({
  id: '/lecturer',
  path: '/lecturer',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerSetupRoute = LecturerSetupRouteImport.update({
  id: '/lecturer-setup',
  path: '/lecturer-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const RepRoute = RepRouteImport.update({
  id: '/rep',
  path: '/rep',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerIndexRoute = LecturerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerActivityRoute = LecturerActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerClassesRoute = LecturerClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => LecturerRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioClassRoute = StudioClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => StudioRoute,
} as any)
const StudioGroupRoute = StudioGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => StudioRoute,
} as any)
const StudioJourneyRoute = StudioJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => StudioRoute,
} as any)
const StudioOpportunityRoute = StudioOpportunityRouteImport.update({
  id: '/opportunity',
  path: '/opportunity',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSelectRoute = StudioSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSimulationRoute = StudioSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => StudioRoute,
} as any)
const StudioVentureRoute = StudioVentureRouteImport.update({
  id: '/venture',
  path: '/venture',
  getParentRoute: () => StudioRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerGroupsGroupIdRoute = LecturerGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => LecturerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lecturer': typeof LecturerRouteWithChildren
  '/lecturer-setup': typeof LecturerSetupRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/owner': typeof OwnerRoute
  '/rep': typeof RepRoute
  '/studio': typeof StudioRouteWithChildren
  '/lecturer/activity': typeof LecturerActivityRoute
  '/lecturer/classes': typeof LecturerClassesRoute
  '/studio/class': typeof StudioClassRoute
  '/studio/group': typeof StudioGroupRoute
  '/studio/journey': typeof StudioJourneyRoute
  '/studio/opportunity': typeof StudioOpportunityRoute
  '/studio/select': typeof StudioSelectRoute
  '/studio/simulation': typeof StudioSimulationRoute
  '/studio/venture': typeof StudioVentureRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/lecturer/groups/$groupId': typeof LecturerGroupsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lecturer-setup': typeof LecturerSetupRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/owner': typeof OwnerRoute
  '/rep': typeof RepRoute
  '/lecturer/activity': typeof LecturerActivityRoute
  '/lecturer/classes': typeof LecturerClassesRoute
  '/studio/class': typeof StudioClassRoute
  '/studio/group': typeof StudioGroupRoute
  '/studio/journey': typeof StudioJourneyRoute
  '/studio/opportunity': typeof StudioOpportunityRoute
  '/studio/select': typeof StudioSelectRoute
  '/studio/simulation': typeof StudioSimulationRoute
  '/studio/venture': typeof StudioVentureRoute
  '/lecturer': typeof LecturerIndexRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/lecturer/groups/$groupId': typeof LecturerGroupsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lecturer': typeof LecturerRouteWithChildren
  '/lecturer-setup': typeof LecturerSetupRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/owner': typeof OwnerRoute
  '/rep': typeof RepRoute
  '/studio': typeof StudioRouteWithChildren
  '/lecturer/activity': typeof LecturerActivityRoute
  '/lecturer/classes': typeof LecturerClassesRoute
  '/studio/class': typeof StudioClassRoute
  '/studio/group': typeof StudioGroupRoute
  '/studio/journey': typeof StudioJourneyRoute
  '/studio/opportunity': typeof StudioOpportunityRoute
  '/studio/select': typeof StudioSelectRoute
  '/studio/simulation': typeof StudioSimulationRoute
  '/studio/venture': typeof StudioVentureRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/lecturer/groups/$groupId': typeof LecturerGroupsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lecturer'
    | '/lecturer-setup'
    | '/login'
    | '/onboarding'
    | '/owner'
    | '/rep'
    | '/studio'
    | '/lecturer/activity'
    | '/lecturer/classes'
    | '/studio/class'
    | '/studio/group'
    | '/studio/journey'
    | '/studio/opportunity'
    | '/studio/select'
    | '/studio/simulation'
    | '/studio/venture'
    | '/lecturer/'
    | '/studio/'
    | '/api/auth/$'
    | '/lecturer/groups/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lecturer-setup'
    | '/login'
    | '/onboarding'
    | '/owner'
    | '/rep'
    | '/lecturer/activity'
    | '/lecturer/classes'
    | '/studio/class'
    | '/studio/group'
    | '/studio/journey'
    | '/studio/opportunity'
    | '/studio/select'
    | '/studio/simulation'
    | '/studio/venture'
    | '/lecturer'
    | '/studio'
    | '/api/auth/$'
    | '/lecturer/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/lecturer'
    | '/lecturer-setup'
    | '/login'
    | '/onboarding'
    | '/owner'
    | '/rep'
    | '/studio'
    | '/lecturer/activity'
    | '/lecturer/classes'
    | '/studio/class'
    | '/studio/group'
    | '/studio/journey'
    | '/studio/opportunity'
    | '/studio/select'
    | '/studio/simulation'
    | '/studio/venture'
    | '/lecturer/'
    | '/studio/'
    | '/api/auth/$'
    | '/lecturer/groups/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LecturerRoute: typeof LecturerRouteWithChildren
  LecturerSetupRoute: typeof LecturerSetupRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OwnerRoute: typeof OwnerRoute
  RepRoute: typeof RepRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer': {
      id: '/lecturer'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof LecturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer-setup': {
      id: '/lecturer-setup'
      path: '/lecturer-setup'
      fullPath: '/lecturer-setup'
      preLoaderRoute: typeof LecturerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rep': {
      id: '/rep'
      path: '/rep'
      fullPath: '/rep'
      preLoaderRoute: typeof RepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/': {
      id: '/lecturer/'
      path: '/'
      fullPath: '/lecturer/'
      preLoaderRoute: typeof LecturerIndexRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/activity': {
      id: '/lecturer/activity'
      path: '/activity'
      fullPath: '/lecturer/activity'
      preLoaderRoute: typeof LecturerActivityRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/classes': {
      id: '/lecturer/classes'
      path: '/classes'
      fullPath: '/lecturer/classes'
      preLoaderRoute: typeof LecturerClassesRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/class': {
      id: '/studio/class'
      path: '/class'
      fullPath: '/studio/class'
      preLoaderRoute: typeof StudioClassRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/group': {
      id: '/studio/group'
      path: '/group'
      fullPath: '/studio/group'
      preLoaderRoute: typeof StudioGroupRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/journey': {
      id: '/studio/journey'
      path: '/journey'
      fullPath: '/studio/journey'
      preLoaderRoute: typeof StudioJourneyRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/opportunity': {
      id: '/studio/opportunity'
      path: '/opportunity'
      fullPath: '/studio/opportunity'
      preLoaderRoute: typeof StudioOpportunityRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/select': {
      id: '/studio/select'
      path: '/select'
      fullPath: '/studio/select'
      preLoaderRoute: typeof StudioSelectRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/simulation': {
      id: '/studio/simulation'
      path: '/simulation'
      fullPath: '/studio/simulation'
      preLoaderRoute: typeof StudioSimulationRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/venture': {
      id: '/studio/venture'
      path: '/venture'
      fullPath: '/studio/venture'
      preLoaderRoute: typeof StudioVentureRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/groups/$groupId': {
      id: '/lecturer/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/lecturer/groups/$groupId'
      preLoaderRoute: typeof LecturerGroupsGroupIdRouteImport
      parentRoute: typeof LecturerRoute
    }
  }
}

interface LecturerRouteChildren {
  LecturerActivityRoute: typeof LecturerActivityRoute
  LecturerClassesRoute: typeof LecturerClassesRoute
  LecturerIndexRoute: typeof LecturerIndexRoute
  LecturerGroupsGroupIdRoute: typeof LecturerGroupsGroupIdRoute
}

const LecturerRouteChildren: LecturerRouteChildren = {
  LecturerActivityRoute: LecturerActivityRoute,
  LecturerClassesRoute: LecturerClassesRoute,
  LecturerIndexRoute: LecturerIndexRoute,
  LecturerGroupsGroupIdRoute: LecturerGroupsGroupIdRoute,
}

const LecturerRouteWithChildren = LecturerRoute._addFileChildren(
  LecturerRouteChildren,
)

interface StudioRouteChildren {
  StudioClassRoute: typeof StudioClassRoute
  StudioGroupRoute: typeof StudioGroupRoute
  StudioJourneyRoute: typeof StudioJourneyRoute
  StudioOpportunityRoute: typeof StudioOpportunityRoute
  StudioSelectRoute: typeof StudioSelectRoute
  StudioSimulationRoute: typeof StudioSimulationRoute
  StudioVentureRoute: typeof StudioVentureRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioClassRoute: StudioClassRoute,
  StudioGroupRoute: StudioGroupRoute,
  StudioJourneyRoute: StudioJourneyRoute,
  StudioOpportunityRoute: StudioOpportunityRoute,
  StudioSelectRoute: StudioSelectRoute,
  StudioSimulationRoute: StudioSimulationRoute,
  StudioVentureRoute: StudioVentureRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LecturerRoute: LecturerRouteWithChildren,
  LecturerSetupRoute: LecturerSetupRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OwnerRoute: OwnerRoute,
  RepRoute: RepRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
